Add profile-guided optimization support
chen3feng/blade-build pull request #1003
Opened 2023-01-11 04:09 UTC by angrygiraffe

Add two profile-guided optimization realated command line arguments, '--profile-generate' and '--profile-use'. 
Please refer to the reference https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Instrumentation-Options.html for details.

2023-01-11 07:33 UTC, chen3feng requested changes

2023-01-11 07:33 UTC, chen3feng commented on src/blade/backend.py
> +            if len(pgo_gen_dir) == 0:
```
if not pgo_gen_dir:
```
https://google.github.io/styleguide/pyguide.html#214-truefalse-evaluations
下同

2023-01-11 08:07 UTC, angrygiraffe commented on src/blade/backend.py
> +            if len(pgo_gen_dir) == 0:
好的，已按google python风格调整

2023-01-30 05:55 UTC, chen3feng approved these changes

2023-01-30 05:55 UTC, merged