fix: exceed maximal length of bash when linking
chen3feng/blade-build pull request #927
Opened 2021-05-18 12:33 UTC by atlantidewang

2021-05-18 13:30 UTC, chen3feng requested changes

2021-05-18 13:30 UTC, chen3feng commented on src/blade/backend.py
> +        link_args = '-o ${out} ${intrinsic_linkflags} ${linkflags} ${target_linkflags} @${out}.rspfile ${extra_linkflags}'
叫 `rsp` 吧，短点。

2021-05-18 13:30 UTC, chen3feng commented on src/blade/backend.py
> +                           command= 'touch ${out}.rspfile &&' + ' ' + ld + ' ' + link_args,
需要touch吗？

2021-05-18 13:30 UTC, chen3feng commented on src/blade/backend.py
> +        # link might have a lot of object files exceeding maximal length of a bash command line.
Linking
句子首字母大写

2021-05-18 13:30 UTC, chen3feng commented on src/blade/backend.py
> +        # using response file can avoid this situation.
situation 换成 resolve this problem 吧

2021-05-19 02:20 UTC, atlantidewang commented on src/blade/backend.py
> +                           command= 'touch ${out}.rspfile &&' + ' ' + ld + ' ' + link_args,
测了一下确实不需要

2021-05-19 03:55 UTC, merged